### ISSUE TITLE
March Madness/Registration

### ISSUE THREAD

**Issue by jschanker** [zach111694/molloyLife#6]
If the Math and Computer Studies Department has a March Madness challenge with the Business Division as we spoke about last semester, we could use group brackets on a site such as ESPN for monitoring the results.  Given that this is a student activity however, I thought it might be nice if the Molloy Life app could gather the content from such a site.

Also, with registration coming up, perhaps we could get the information from Lions Den and display it in a mobile friendly format.  We could also offer additional features such as the ability to view courses from two different subject areas.  Maybe we could even incorporate functionality from the advising app.

Any interest in adding any of this functionality to the app?

**Comment by jcdesimp** [comment]
@jschanker Any site where I can view some more information about this march madness event?
I'm not to sure about aiming for registration and MM as a release date. If we plan to include these features then the next registration would probably be a more reasonable time to have it ready by. Given our development speed so far and the fact that this is mainly a side project for us, I can't see us having a shippable product by then.

These features would be an interesting addition though, at least for registration. The march madness thing seems a bit out of scope though but I'd have to learn more about it. Registration info seems like something that every student would be able to benefit from thought.

We would need to know more about methods for accessing information in Lion's den (which I'm guessing is your class registration system?). If they have some sort of data API that can be accessed without needing to authenticate first that that would be perfect since all we are doing is displaying information to students.

Any additional info you could get would be much appreciated, thanks.

**Comment by jschanker** [comment]
@jcdesimp The March Madness event hasn't been organized yet.  The idea was proposed to me last semester by a professor in the Business Department (Greg Sand), but I'd have to follow up on it in order for it to happen.  Although it's not of general interest to all students, I figured it might be a good hook for getting some students to check out and use this app.

I agree that we probably won't have a stable version of the Molloy Life app by the end of March, but I was wondering if we wanted to beta test it before then.  A potential upside could be getting user feedback to help us shape a better product while a potential downside could be leaving the unpolished app's users with a bad first impression of it.

Students can look up and register for courses on Lions Den, but it also provides access to Molloy's LMS, Degree Audit, etc.  It's located at lionsden.molloy.edu .  People can do a course search without logging in,  I e-mailed our Director of MIS and Operations (Mike Olivo) to find out if there's any sort of data API for the Course Search, and I'll let you know what I find out.  Even if there isn't a publicly accessible data API, we could still get the data by parsing the HTML obtained via GET and POST requests.

**Comment by jcdesimp** [comment]
@jschanker sure, we could start experimenting with it or scraping it directly depending on whether or not an API is in place.

**Comment by jschanker** [comment]
@jcdesimp He responded that there's no API in place so scraping it is.

**Comment by jcdesimp** [comment]
@jschanker scraping a college class registration system... This should be interesting, haha.

**Comment by jschanker** [comment]
@jcdesimp This is definitely going to be interesting!  Currently, there's a mechanism in place that redirects you home when you accidentally click a Submit button twice or (sometimes) when you hit the back button with the irritating message, "You have been redirected to this page because you attempted to navigate using your browser's Back or Refresh button. To avoid this in the future, make sure you navigate using the links and buttons that are part of the Portal interface." @SantiVargas , @zach111694  I know you enjoy seeing that message as much as I do.  

Some early experimenting is giving me an idea of how this might be being implemented.  I saved the source of the Course Search page and did a course search from the local version of the page.  The first time I do this, I get the course results.  But if I do this again, I get redirected to the page with this error message.  I changed the POST request to a GET request to see the data that's getting sent as a whole.  I then revisited the Course Search page and again viewed and saved the source, changing the POST request to a GET.  A comparison of the transmitted data shows that the only difference between what's being sent each time is the value of the hidden __BrowserRefresh field.  I'm assuming the system uses this field to keep track of requests and deny repeat ones.  

To implement the Course Search feature for the Molloy Life app, it would then seem that each time we want to send a POST request to get the course data, we would first need to send a GET request to get the unique value of the __BrowserRefresh field.

On an interesting related note, I heard a story about students at another school who used a bot to be notified if and when full classes they wanted to take opened up.

**Comment by jcdesimp** [comment]
@jschanker I think all college class registration systems are terrible by nature. RIT's is just a single-page PeopleSoft application. Hitting the back button pretty much makes you have to start your session over. 

The Computer Science House here created a schedule maker that hooks into our registration system to allow students to sort their schedule in a more user friendly way before going on to the main system to enroll. Also more recently another student run organization created a simple interface for enrollment without needing to log in to the main system. I'm not really sure how these sites get the info, if it's scraping then it must be difficult since I'm pretty sure the registration site won't work if you have javascript off. 

But yea I think it'll mostly be trial and error trying to figure out the best way to implement this.

**Comment by jschanker** [comment]
That's interesting; I wonder how many other schools are creating workarounds for poor registration systems.  I don't remember having many complaints about the registration systems in place when I went to college and graduate school.  The only problem I had in college was that the servers weren't going to be able to handle the massive surge of requests at the starting time of 7am on a registration day.  What this meant (and this happened to me) was that you could attempt to sign up for an open class and wait only to have the request time out on you.  Upon a retry, one of the classes that was open when you tried to register for it could now be closed.  That was certainly very frustrating.

Regarding the script, I'm currently getting a "403 - Forbidden: Access is denied." error when attempting to send a POST request to get the results from the Course Search,  I'd have to investigate this further, but maybe you have more experience with web crawlers to help with this issue?

Here are a couple details that may be helpful:
(_) You don't seem to need to include the very long value for the __VIEWSTATE field in the request.
(_) THE ASP.NET_SessionId cookie value seems to be the only one that's required.

**Comment by jschanker** [comment]
Never mind, I got it; I wasn't printing request headers correctly.
